export const evaluationTextMapping = {
    "i-i": {
        "insights": [
            "You believe nobody completes anyone. You have your own interests, hobbies, and friends, and you might like to keep all that (or some of that) separate even when you are together. Being in a partnership doesn't mean you stop being who you are, self-care and all that. You want to make sure you care for yourselves as much as you care for each other.",
            "You and [Compatibility Name] see 'I' to 'I' when it comes to being a team of sorts. This is the type of connection that makes time feel relative: no matter how long it's been since you last saw each other, it's like no time passed. Events in your lives sometimes organically overlap, or sometimes you need to reserve a spot in your calendar's empty slot to make sure you can connect. No need to force anything. The two of you meet up whenever is clever, you each have your own worlds that you prefer to keep separate, the only challenge may be to sometimes sacrifice a little me time for more we time.",
            "It may be the case that [Compatibility Name] is your grounding force outside of your romantic relationships. You and [Compatibility Name] won't have trouble respecting each other's need for time alone time, making the times you do meet up more appreciated and cherished, and not to be taken for granted. Keep in mind that the beauty of independent worlds can also be their flaw. If you leave it all to chance you two might drift apart. If you don't want the friendship to slip away, you'll need some intentionality. Making the effort to reach out of your private bubbles to connect will ensure the bond stays strong and treasured.",
            "There's nothing sexier than a little magnetic mystery, and that's what you can get in a partnership where 'I' meets 'I'. It makes the shared moment a sacred rendezvous, a treasured glimpse into each other's secret magical realms. Just be careful not to isolate too much. In order to build a deep connection with [Compatibility Name], you can't live in 2 separate worlds. You'll need to also make time for each other, building a bond takes some effort. Sacrificing some privacy for quality time with your partner will provide a key ingredient to a thriving partnership."
        ]
    },
    "we-i": {
        "insights": [
            "You believe in creating joint memories and fully engaging in the present with your significant other. Venturing into your distinct realms is how you integrate yourselves into each other's lives. For you, nothing surpasses the importance of quality time-it's the essence of your connection. If that's missing, you question the value of the partnership.",
            "Sometimes your openness might make it hard for you to understand [Compatibility Name]'s need for space. You might be wondering, \"If i'm always down to have them around, why are they so picky and choosy with me?\" It's not about keeping score and you shouldn't take it personally. It's about understanding each other's comfort zones. Just because you feel at ease bringing them along in your social circles, doesn't mean they'll feel the same. That said, you should advocate for your needs, and reflect on how much \"we\" time you need with [Compatibility Name] either as a friend or a partner.",
            "Yep, you've got it right, your friend [Compatibility Name] is a little on the private side. Even when you have the same interests, sometimes they'll wanna just do their own thing. And that does not have to be a bad thing. Respect their distance and focus on the quality time you do share. That'll matter more when building a friendship with [Compatibility Name] than how many different social circles and hobbies you share.",
            "Ok, so, obviously spending time with your partner is vital in a relationship. But being with someone like [Compatibility Name], it means respecting their need for solitude while expressing your need for togetherness. Now there are extremes, so learn to know when either of you is pushing too far. There's this thing called compromise, and you're going to have a valuable opportunity to work on it in this relationship. Nothing a good talk can't solve. Advocate for your needs, and hopefully, you and [Compatibility Name] will have a compatible kind of flexibility, a sweet spot where the two of you can find each other between their 'I-ness' and your 'We-ness'."
        ]
    },
    "we-we": {
        "insights": [
            "You want to create shared memories, be in the moment with your partner. Exploring your different worlds is how you become a part of each other's lives. For you, quality time is top-tier important. It comes before everything else, otherwise you might feel like, what's the point of a partnership, ya know.",
            "You and [Compatibility Name] are totally down with a cozy mishmash of groups, whether its family, friends, partners or maybe just the two of you squeezing in as much time together as you can. You know the motto, 'The more the merrier', life is one big party everyone is invited to. Just keep an eye out for overdoing the togetherness. There is also value in working a little 'you time' into your busy social calendars. Finding the healthy balance between joinging forces and sometimes rolling solo will keep things fresh and fun.",
            "Friendship with [Compatibility Name] could look like a never-ending exchange of invites. Their friends. Your friends. It's one big open club sharing love. Just remember, there's beauty in boundaries too. Enjoy the continual mixing of worlds, but without some unspoken obligation. You might not always be up for every invite, and that's totally ok. Embrace the shared experiences but maintain the freedom to opt-out when it suits you. It's not personal!",
            "With [Compatibility Name], it's quality time whenever is clever. An open buffet of shared experiences. You two will love practicing the art of merging worlds. Your time spent together is just as important as the time you spend in each other's worlds. Just be careful not to smother each other. A little separation is healthy. A solo adventure or a hangout with your bestie without your significant other can be refreshing. And it goes both ways. Mutual understanding and respecting the need for the occasional breather will add extra spice to your shared journey."
        ]
    },
    "i-we": {
        "insights": [
            "You cherish your independence and believe that a fulfilling relationship doesn't require two people to be inseparable. You have passions, hobbies, and friends that are uniquely yours, and you value maintaining those aspects of your life even when you're in a partnership. You understand that being in a relationship doesn't mean losing your individuality; instead, it's about supporting each other's growth and self-care.",
            "Sometimes your need to protect your peace might be at odds with [Compatibility Name]'s need for your time and attention whether they're a friend, partner, or colleague. where you see boundaries and intrusion, they see opportunities for inclusion, eager to mesh everyone into everything. getting the dynamic you want with [Compatibility Name] means communicating openly, recognizing when you can be flexible, and when to maintain your space.",
            "Forging a friendship with [Compatibility Name] might be a constant dance between blending and separating. You prefer things to be siloed (family, friendships, partners, etc), and you value your alone time, your own little universe. [Compatibility Name], though? They're all about gathering the troops by roping everyone together, merging worlds at every chance. This contrast could have two effects on you: you may value their ability to pull you out of your universe; or someimes, you might be overwhelmed by their need to always be making plans. Or maybe a bit of both depending on your mood. Let them know how you're feeling. Showing up for [Compatibility Name] while also subtly establishing your limits can speak volumes in maintaining a balanced friendship.",
            "The journey with [Compatibility Name] depends on where you both land on the \"I\" and \"we\" scales. Knowing yourself is crucial and compromise is key. You'll have to gauge your willingness to intertwine your worlds and be mindful of how much [Compatibility Name] can adapt to your preference for separation and 'you time'. It's not about clinging-'we' individuals just value shared moments more. Ongoing self-reflection to discern where your lines are drawn and where there's room to bend a little will go a long way."
        ]
    },
    "reflective-reflective": {
        "insights": [
            "You need space and time alone to process your thoughts and feelings when there's a disagreement. You don't want to just react, you want to intentionally respond. So, you take some time to think, no big deal. You gotta feel everything out before you can figure out what you really mean to say.",
            "As two reflective communicators, you and [Compatibility Name] might as well be telepathic, with no need to say, 'Let's talk about it later,' cause you'll both already be on that same page. The two of you understand the importance of silence. It's like a language. In an argument, it means 'I don't want to jump the gun and say something I'll regret. Let me get my thoughts down right.' But be careful. It's one thing to pause and reflect instead of lashing out, it's quite another to overthink things and let an important conversation get away by waiting too long.",
            "It's all good, friends may butt heads. There's no need to explain on the fly. You and [Compatibility Name] both ought to know that the patch-it-up text will be coming soon, doesn't matter who makes the first move, and maybe that breather is all that's needed either to let the argument go or to finally discuss things calmly. But friendships do need the space to sometimes have those uncomfortable conversations, and it's better not to avoid them. While it may seem like the two of you get along with no issues or conflict, keep an eye out for any resentment brewing beneath the surface. It's better to air it all out before letting things build up.",
            "In a partnership, reflective communicators like you and [Compatibility Name] instinctually handle your conflicts in similar ways. Timeouts will feel natural and healthy. It'll be through the separate silent spaces between fights that you and [Name] will find each other again. Reflection alone helps you find the right words to say when you and [Compatibility Name] decide to revisit an argument and work it out. But remember, conflicts don't resolve themselves. Having difficult conversations with care and honesty is vital to any healthy relationship. Since you know where each other is coming from, this pairing is an opportunity to practice confronting conflict together."
        ]
    },
    "reflective-active": {
        "insights": [
            "You require solitude and time to digest your feelings and thoughts when faced with a conflict. You prefer to respond with intention rather than react hastily. For you, taking some time to ponder is natural. You believe in experiencing your emotions thoroughly before you can express what you genuinely mean.",
            "So it's like a dance of opposites with [Compatibility Name] when tension hits: you're stepping back, they're stepping forward. By the time you're calm and collected and ready to talk it over, they might think, \"Why are we still on this?\" Kinda like catching a moving train, isn't it? But here's some insight: active communicators like [Compatibility Name] might peg you as distant or, I don't know, a bit chilly because you're not diving into the deep end right away. Make it clear that you care, but that you're not about the now and are more about the later. Let them know up front how long you'll need because letting the 'later' slip into 'never' is a missed opportunity to connect (and may ultimately cause resentment between you two).",
            "[Compatibility Name] is wondering why you left them on read. It's not like you're ghosting or dodging them when they want to have it out about something and you're still assessing your feelings; but to build trust in your friendship, you might wanna meet them somewhere in the middle. Let them into your inner world a little bit, maybe with a text that says 'I'm still thinking on it. Can we chat later tonight?' Sure, creating that boundary might be hard at first, but every time you loop back for a heart-to-heart, a true friend gets it and learns your rhythm.",
            "Now, with [Compatibility Name], sure it might feel like you're juggling fire and ice, but with respect, understanding, and a shared search for that middle ground, you may just find the golden ticket to working things out. You are who you are, and your active partner, with some patience, will understand your need to reflect over spats before diving back in. And you'll get the hang of not pushing pause for too long. Remember that conflict with [Compatibilty Name] isn't a bad thing! Resolving your differences may be the key to unlocking a deeper bond in your relationship."
        ]
    },
    "active-active": {
        "insights": [
            "You're probably not one to shy away from expressing your feelings, directly. Moments when you and your partner don't see eye-to-eye, for you, are priceless opportunities for deeper understanding and getting closer. You think there's no time like the present to work something out, and it's better to never let the moment get away.",
            "You two put everything out in the open. To outsiders, active communicators like you and [Compatibility Name] seem to speak faster than you think. But you own it. Conflicts? You'll sort them right away. Plans? they're made in an instant. Feelings? You're not gonna hide them. But be careful, moving so quickly can also cause things to get blown out of proportion during a heated disagreement. Practice listening before trying to get the next word in. It's unlikely that every thought bubble needs to manifest into words. Slowing down so you don't say something you'll regret can actually empower your active style of communication, keeping it real without sacrificing honesty.",
            "Time sure flies when you and a friend like [Compatibility Name] get into conversation. There are no filters with you two. Your version of honesty is unflitered and raw. This can make for a special friendship. If something is on your mind, you know you can go to [Compatibily Name] to talk it out. In a conflict, though, things could get slippery with this matchup. If you are always waiting for the next chance to make your points, you may not feel responsible for what ends up coming out of your mouth, and the two of you will find yourselves standing on thin ice. It's all about hitting that sweet spot: a balance of speaking your mind carefully and holding back to really listen.",
            "As two active communicators in a partnership, you and [Compatibility Name] can share so many words you could probably fill a library. Because you're quick to address conflict and express your feelings, people may perceive you as having the ideal relationship. Stay vigilant for times when you may need to create space for silence, especially when the sparks are flying in an argument. the big risk is that heated words become darts, sharp extensions of thoughts that should've been left unspoken or softened for easier impact. Timing is pretty much the secret sauce, learned over, well, time, and so that instead of making a melodrama out of something trivial, those free-flowing words can be used to either fix a hiccup or resolve a serious problem."
        ]
    },
    "active-reflective": {
        "insights": [
            "You're likely comfortable with openly expressing your emotions. When you and your partner disagree, you see it as a valuable chance to gain a deeper understanding and strengthen your bond. You believe in addressing issues promptly, as letting opportunities slip by is not your style.",
            "As an active communicator, sometimes you might feel like your immediate need to say it all out loud right then and there crashes into [Compatibilty Name]'s wall of silence. You value expression, and may let fly whatever is on your mind without knowing how it'll land until much later-if at all. And if they hit you back after the fact, it might catch you off guard cause you may have already moved past it. Scope out the signals: are they cool to chat, or is it time to back off and give them some space? [Compatibilty Name] may not always give you a clear signal, so you'll have to learn their tells.",
            "No, you're not being ghosted, you're still friends, but your reflective pal is taking some time to figure out their response. So don't take it personally if no matter what you say they barely engage. And as friends, respect their pace, even if you're itching for an answer and feel tempted to coax one out of them by talking more and more. That'll only make things worse. Say your piece but be mindful of overstepping. Give your friend some breathing room so they feel comfortable coming back to talk. In fact, you could end a text with 'I know you need some time to think on it, and that's okay.' Knowing that you get them might encourage [Compatibility Name] to communicate more actively with you in the future.",
            "There's a magic code to unlocking the wall of silence your reflective partner might erect after an argument, and it's called patience. Yep, it'll be hard. You might feel loaded with unexpressed feelings, and start over-speaking before realizing the impact of your words, especially since you won't get immediate feedback. Challenge yourself to slow the rhythm down, and be careful to not let it bleed over into building resentment towards [Compatibility Name]. Let those thoughts marinate without immediate release, and give your partner some processing time. Be open to discussing things even when you might be over it. And if they're taking their sweet time, a gentle nudge to talk it out never hurts, especially if you remind them that you understand and respect their need to reflect."
        ]
    },
    "emotional-emotional": {
        "insights": [
            "For you, emotional closeness comes before physical contact. When you feel emotionally connected and are able to share the most intimate parts of yourself with your partner, your desire for them soars. It's all about feeling emotionally safe with your partner, like you can rely on them to be available for your needs, that bonds you.",
            "With [Compatibility Name], it's all about that emotional bond, a strong sense of trust and respect for each other, as family, friends, or partners. You can feel that warm vibe just in the way you greet each other, and it whispers, 'With me you're safe. you can count on me.' And as with any good emotional connection, taking it for granted or taking advantage is something to watch out for. Even the strongest emotional connections can come with conditions, and those are usually based on respect and consideration.",
            "If you and [Compatibility Partner] hit it off as friends, you'll cherish connection and trust. You may feel very lucky to have found each other in this life. Whether through shared projects or experiences or just full-on heart-to-hearts, you build an emotional closeness that lets you know you have each other's back. Through thick and thin. Beware of sloppy behavior by taking each other's emotional connection for granted. Make the effort to show up with your best self even though you know that [Compatibility Partner] will be there at your side for the times when you're at your worst.",
            "[Compatibility Name]'s emotional intimacy style can blend in seamlessly with yours, paving the way for a strong bond you can feel at a distance just in each other's presence. That mutual trust and assurance will beat at the heart of your partnership, as long as it's nurtured and protected. Cause, while your emotional bond with [Compatibility] may feel effortless, the two of you will still need to make that extra effort to handle it with care. After all, it's the foundation you both rely on for physical intimacy."
        ]
    },
    "emotional-physical": {
        "insights": [
            "You're probably not one to hold back when it comes to sharing your feelings. Disagreements with your partner are seen by you as golden opportunities to deepen your connection and enhance your mutual understanding. You're of the mindset that there's no better time than the present to resolve matters, and you're keen on not letting any moment pass you by.",
            "Two forms of intimacy, one goal: closeness. But whereas [Compatibility Name] might be reaching out for a friendly hug or a hand to hold, your instinct might be to ask them, 'So how are you REALLY feeling?' Because you need to feel close before you can get close. That's just how it is: they speak in touch. You speak by getting deep. In one way or another, with words or gestures, you'll need to communicate that emotional connection is what paves the way to physical intimacy.",
            "When building a friendship, you keep a bit of physical distance until you feel like long-time friends, so things might start a bit awkward with [Compatibility Name]. They like to create closeness through casual shoulder leans during walks, a little hug when they're feeling down, that kind of thing. But with time, [Compatibility Name] will catch on to how you warm up to them as the trust and familiarity between the two of you grows. You may not speak the same emotional language, but you'll quickly learn how to communicate.",
            "In a romantic partnership with [Compatibility Name], whether with words or body language, you'll need to make it clear from the get-go that you yearn for a sense of trust and connectedness before getting physical. That vibe of unity even when you're apart is what brings you closer. So, you know, gently but firmly, talk it through with [Compatibility Name], because they're the opposite of you. They create closeness by diving right into the physical acts, from hand-holding to having sex. It's the actions that build connection for them. So they may interpret your desire to take it slow as rejection. A proper talk and lots of respect will build the emotional bond you seek, and before you know it, you'll both feel emotionally fulfilled."
        ]
    },
    "physical-physical": {
        "insights": [
            "You see physical contact, like hand holding, back scratches, cuddling, and sex as the most direct way of creating closeness and connection in a relationship. It's what invites you to share who you are and how you feel about who you're with. Everything words fail to say you can feel and express with touch.",
            "Words schmurds, who needs those airy things when you can just embrace in a long, warm hug. And for you and [Compatibility Name], physical contact is just a natural interaction. It's literally (and metaphorically) how you both get close. The only catch is that, hey, getting physical can only take you so far. At some point, you just might wanna talk if your connection is feeling stalled. You two have the opportunity to learn and practice with each other. Be patient!",
            "This friendship likely feels light and fun because you don't easily get into the nitty gritty of emotions. But that's also what might make it hard sometimes to know how close you and [Compatibility Name] really are. While you may feel like best buds, you might not know who they REALLY are. Like deep down who they are. And hey, there's nothing wrong with keeping things light! But if times get hard, do you feel like you can rely on each other? Do you feel safe? These answers should be clear without the physical displays of closeness.",
            "A romantic relationship with [Compatibility Name] can be intensely physical. You might get so swept away and immersed in every form of touch, whether it's playful, affectionate, sensual, or sexual, that you might eventually feel like something is missing. Directly expressing familiarity and love through touch is magical. So is creating some space to feel each other's... emotions. After all, physical sparks can wear off. An emotional bond that doesn't depend solely on physical contact can help make the relationship last long."
        ]
    },
    "physical-emotional": {
        "insights": [
            "You believe that physical contact, including hand-holding, back scratches, cuddling, and sexual intimacy, is the most direct path to creating a deep bond in a relationship. It's through these tactile expressions that you open up and communicate your affection for your partner. Touch is your way of expressing what words cannot, allowing you to feel and convey your emotions.",
            "You may build closeness through physical touch, but [Compatibility Name]? They want to feel your soul before they feel your body. Even a simple pat on the back might be a bit much for them if the trust isn't there yet. So, when you're just starting to get to know [Compatibility Name], you might need to curb that urge to reach out. Instead, focus more on nurturing the connection you share. Your words and good vibes will go a long way.",
            "You might notice that [Compatibility Name] tenses up even when you give them a friendly hug. They're just not like that. Physical contact is something they reserve for those they feel especially close to, and that's something you'll need to earn through sharing time and building trust. Notice their boundaries and communicate about your intimacy style. They'll appreciate that, and in time, they'll be comfortable with a friendly hug.",
            "Brace yourself: that hug, kiss, or even a back scratch that you want to give [Compatibility Name]? It might have to wait if they're not feeling like their best self. Challenge yourself to go against what you're used to with [Compatibility Name] by focusing more on building trust first. Ask them how they're feeling before initiating contact. That's just how they are: they need to feel close to you without always being close to you, you know? You might be like, let's just make up by making love. Well, they're gonna say, 'let's make up and then make love.'"
        ]
    },
    "guarded-guarded": {
        "insights": [
            "Getting to know someone doesn't happen all at once. Being guarded doesn't necessarily mean you aren't open, it just means that you prefer things to unfold organically. You and your partner can't just show each other everything. Your inner worlds are sacred, to be gradually explored. Entrance needs to be earned with trust, and building trust takes\u2026 time.",
            "Getting to know [Compatibility Name] is gonna be a bit like walking through a maze or building a puzzle-you both take it slow, figure things out one step at a time. It's all about building trust and patiently letting things evolve at their own pace. But remember, friendships and partnerships require some level of risk. There are no guarantees no matter how careful you are. At one point you'll have to take off that armor, or what you might end up risking is never getting close at all.",
            "Building a friendship with [Compatibility Name] could easily be a slow journey-and that's how both of you like it. It goes without saying for both of you that trust isn't just handed over, it's built bit by bit. And that's cool. It means you value the connections you make. But, here's the thing, letting the fear of getting hurt dominate your actions can make your friendship kinda surface-level. If you and [Compatibility Name] want to get deeper, you're gonna have to get a little uncomfortable by allowing yourself to be vulnerable.",
            "Starting something romantic with [Compatibility Name] means both of you are gonna be a bit of an enigma to each other for a while. Even amidst the intimate moments. It's cool, mysteries are sexy and fun, and in a way, they offer a sense of safety, at least until you decide it's time to let the walls come down and reveal your true selves. Cause, it's in those genuine, vulnerable moments that you'll find real closeness, and that can only happen by taking down your guard. Use the good times to practice for when tough times eventually come."
        ]
    },
    "guarded-open": {
        "insights": [
            "Discovering someone's true nature is a gradual process. Being reserved doesn't imply a lack of openness; it simply suggests that you favor a natural progression in relationships. You and your partner can't instantly reveal your deepest selves. Your inner sanctuaries are to be delicately navigated, with access granted through earned trust, which naturally requires time to develop.",
            "The ease with which [Compatibility Name] might reveal their secrets might throw you off. You might even be in awe of their openness. You see, [Compatibility Name] is just an open book when it comes to showing the kinds of things that you keep buried. It'll take the two of you to find that middle ground. Don't feel rushed to lay all your cards out, but understand that any kind of meaningful relationship with [Compatibility Name] may mean loosening up those guards a little faster than you're used to.",
            "With [Compatibility Name], you might wanna prepare for a few overshares. It might seem like they don't hold much back. But you know what? They think their open vulnerability is actually what makes them strong, and they might see your guardedness as frustrating, or a bit like hiding. Friendships are built on trust, and it goes without saying that the strength of your bond with [Compatibility Name] will rest on your ability to feel safe with them when you're just being you. No need to force things, but with [Compatibility Name] you might need to lower your guard sooner than usual.",
            "In a romance with [Compatibility Name], they might be scratching their head wondering why you seem so buttoned up when they're wearing their heart on their sleeve. Let them know you are a slower burn in building trust. Compromising to find a middle ground is key for any relationship. You don't want to be rushed into revealing too much too quickly, but [Compatibility Name] won't want to wait forever to receive what they already give: a view of what's on the inside. Take this as a chance to grow beyond your comfort zone by trusting [Compatibiliy Name] and sharing a bit of your inner world."
        ]
    },
    "open-open": {
        "insights": [
            "You don't want to hide. You want you and your partners' strengths and weaknesses out in the open. The full package. The light and the dark. Because it's the only way you can know who you're with. You prefer to get things out in the open to know if you and your partner are a good fit. Why even hold anything back?",
            "The two of you can get really deep, really fast. From day one it'll be like you and [Compatibility Name] know everything about each other. It's like oversharing is your way of saying hello! No time for small talk when there are open books to read, right? Cool. But depending on your relationship, you may need to learn to filter. It's easy for you to open up with [Compatibility Name], but make sure you don't share something you'll later regret.",
            "This can be a very supportive friendship. You and [Compatibility Name] are cool with being personal upfront. No matter how long you've known each other, you two will feel like old friends. Quick reminder though: it's one thing to know a lot about each other's lives, and it's another to actually really know each other. Between all the talking, make sure that you're also listening and absorbing, taking the time to respond thoughtfully. To build closeness and a strong foundation, you'll need the conversations to stick.",
            "This might feel like a match made in heaven, as you two share your deepest thoughts and most vulnerable feelings. You and [Compatibility Name] will have no problem laying it all out there with nothing to hide. But things can move really quickly with two open people, meaning that you might get caught up in all the words without paying much attention to the actions. Spend some time sharing experiences, living through the ups and downs and all arounds together, and making sure your actions get some equal playtime to all the words."
        ]
    },
    "open-guarded": {
        "insights": [
            "You have no interest in hiding who you are. You want both you and your partner's qualities and flaws to be visible. The entire spectrum. The highs and the lows. It's the only way, in your opinion, to truly grasp the essence of your partner. You favor laying everything out in the open to assess whether you and your partner are well-matched. Why withhold anything at all?",
            "Don't take it personally, [Compatibiilty Name] takes their time to get personal. Being the open book that you are can catch the guarded people off guard. And that's fine, you do you, just don't expect them to be the same way. They might get there, but they'll need a little time. Patiently giving [Compatibility Name] the time and space to feel safe with you will encourage them to share their world like you do.",
            "[Compatibility Name] needs you to earn their trust over time through shared experiences. You're open with people from the get-go, and [Compatibility Name] might dig that about you, or they might find it awkward. Either way, you need to be okay with them taking it slow. No scoresheets. you'll see, a strong friendship between the two of you is totally possible if the respect for each other's pacing is mutual. Be patient and encouraging, but not demanding.",
            "Jumping into something romantic with [Compatibility Name] will give you the chance to think outside the box. You may even learn to love a little mystery. It can make things exciting. And yeah, it's normal to want your partner to be as open as you. You're as excited to explore their inner world as you are to share yours. If only they'd hurry it up a little bit, right? Well, of course you should advocate for your needs, you want to get to know the person you're with and you should not have to wait forever. But you may be surprised to see that giving them the space to open up at their own pace might actually be what earns you their trust and takes their guard down."
        ]
    },
    "exploring-exploring": {
        "insights": [
            "You're not prioritizing a relationship right now. You're not really looking for anything in particular. You're seeking to discover whatever life has to give, your priority being the work you're doing on yourself, or your job, or school, or family, as you figure out what you want. You're just going with the moment.",
            "[User Name] is a [Number], and [Compatibility Name] is a [Number], so you're both exploring life, not prioritizing romantic relationships right now.",
            "You and [Compatibility Name] are just out there discovering life, going with the flow, learning about the world and your place in it. Neither of you are looking for a serious relationship right now, so you may wanna use this time to build a strong friendship.",
            "You won't be rushing to label anything. Not having expectations leaves room for endless possibilities, such as some good fun in a casual fling, or...maybe something else? Who knows what may arise when you're open to what life brings."
        ]
    },
    "exploring-connecting": {
        "insights": [
            "You're not prioritizing a relationship right now. You're not really looking for anything in particular. You're seeking to discover whatever life has to give, your priority being the work you're doing on yourself, or your job, or school, or family, as you figure out what you want. You're just going with the moment.",
            "[User Name] is a [Number], and [Compatibility Name] is a [Number], so they're prioritizing romantic relationships a little more than you right now.",
            "Right you now you're just learning about the world and about yourself, open to what life brings you. That could include striking up a new and true friendship with [Compatibility Name]. Thing is, they're focusing a little more on dating (if they're single) or their partner. So be sure to make space for each other's priorities, and offer mutual support along the way.",
            "You're not looking to be tied down with labels or anything like that, prefering casual fun on your path of self-discovery. But [Compatibility Name] seeks something more substantial than just-for-fun vibes. Clarity of intentions will prevent misunderstandings. And if there's a romantic spark, a bond could form somewhere between casual and committed, if you're willing to meet [Name] somewhere in the middle."
        ]
    },
    "exploring-bonding": {
        "insights": [
            "You're not prioritizing a relationship right now. You're not really looking for anything in particular. You're seeking to discover whatever life has to give, your priority being the work you're doing on yourself, or your job, or school, or family, as you figure out what you want. You're just going with the moment.",
            "[User Name] is a [Number], and [Compatibility Name] is a [Number], so they're prioritizing romantic relationships a lot more than you right now.",
            "So, [Compatibility Name] is seeking the real-deal romantic relationship, while you're busy world-exploring and soul-searching. But friendship can be found between opposite walks of life, and make for some entertaining conversations. With so much to learn from each other, you both could end up becoming part of each other's support system.",
            "Alright, this pairing is likely to be a total mismatch...unless you're ready to begin a whole new chapter in your life. See, [Compatibility Name] is out here searching for a lasting romantic partner. And you're kinda cruising, learning about life with no need to commit. So unless you're up for a major shift, let's be honest and steer clear of romance together. Cool? Cool."
        ]
    },
    "connecting-exploring": {
        "insights": [
            "You're prioritizing making connections with people. You're seeking something with substance but not concerned with any promise of permanence. You want something more meaningful than wild fun, so while you'd like to leave things open, your one condition is that, whatever happens, it should matter.",
            "[User Name] is a [Number], and [Compatibility Name] is a [Number], so they're not prioritizing romantic relationships as much as you are right now.",
            "You may appreciate [Compatibility Name]'s free-spirited ways as they prioritize figuring out their life. And that's cool. But you're making space for something of substance, and preferably a little romantic. So, as friends, the two of you can build a bond through shared experiences and support each other's separate search.",
            "Be real clear on what you want, cause [Compatibility Name] is in total exploratory mode, focused on other priorities, and your main condition is a soulful connection with some romance, even if the relationship is short-term. Have the talk, and if they're up for something meaningful, then the two of you can discover life (and yourselves) together."
        ]
    },
    "connecting-connecting": {
        "insights": [
            "At this point, you're emphasizing the importance of connecting with others. You're in search of a relationship that holds meaning, but you're not preoccupied with its longevity. You're aiming for something more profound than just casual fun, so although you're willing to see where things go, your primary condition is that whatever transpires should be significant.",
            "[User Name] is at a [Number] on the readiness scale, and [Compatibility Name] is [Number], indicating a mutual prioritization of deepening the relationship further. This equal footing in terms of relationship readiness suggests that both parties are equally invested in taking the next steps to connect on a more significant level.",
            "In the realm of friendship, [Compatibility Name] becomes a mirror reflecting your own desires for connection. Together, you navigate the complexities of trust and vulnerability. The shared journey involves discovering mutual interests, offering support during times of need, and celebrating each other's successes. This phase is crucial for establishing a friendship that is both enriching and enduring.",
            "When considering a partnership, [Compatibility Name] stands beside you as an equal partner in the quest for a deeper bond. The 'Connecting' stage here means engaging in conversations about future aspirations, values, and dreams. It's about building a relationship that not only withstands the test of time but also fosters personal growth and mutual understanding. The emphasis is on creating a partnership where both individuals feel seen, heard, and valued."
        ]
    },
    "connecting-bonding": {
        "insights": [
            "Right now, your priority is forming meaningful connections with people. You're seeking something substantial, but you're not fixated on long-term commitment. You desire something deeper than mere excitement, so while you're keeping an open mind, your only stipulation is that whatever develops should be impactful.",
            "[User Name] is at a [Number] on the readiness scale, and [Compatibility Name] is at a [Number], indicating that while you're looking to deepen connections, [Compatibility Name] is ready to fully commit and form a lasting bond. This difference in readiness levels suggests that [Compatibility Name] might be seeking a more profound level of commitment and emotional investment at this time.",
            "In friendship, this difference in readiness might manifest in the way [Compatibility Name] is more eager to share personal details, seek emotional support, and invest in the friendship on a deeper level. It's important to navigate this stage with open communication and understanding, acknowledging each other's boundaries and readiness levels.",
            "In a partnership, [Compatibility Name]'s bonding readiness signifies a desire for a committed and long-term relationship. This stage involves not just emotional investment, but also discussions about future plans, values, and mutual goals. For a balanced partnership, it's crucial to align your expectations and ensure that both parties are comfortable with the pace and depth of the relationship."
        ]
    },
    "bonding-exploring": {
        "insights": [
            "You're prioritizing bonding with a partner. You're ready to put forth the time and effort to build a partnership that works. Nurturing the bond with your partner to keep it strong is your priority. You realize that while falling in love is easy, staying in love requires dedication and intention, and you think it's more than worth it.",
            "[User Name] is at a [Number] on the readiness scale, indicating a strong focus on bonding and commitment. On the other hand, [Compatibility Name] is at a [Number], showing an inclination towards exploring and keeping options open. This difference suggests that while you are ready for a deep, long-term commitment, [Compatibility Name] might be more interested in casual interactions and exploring multiple connections.",
            "In the realm of friendship, this discrepancy in readiness levels might lead to different expectations. You might be seeking a loyal and dependable friend who is willing to invest time and energy into the relationship, while [Compatibility Name] could be looking for a more light-hearted and flexible companionship, where there is less pressure to commit and more freedom to explore.",
            "When it comes to a romantic partnership, your readiness for bonding means you are looking for a partner who is not only a lover but also a confidant and a teammate. You are prepared to work through challenges together and build a future based on mutual respect and shared goals. In contrast, [Compatibility Name]'s exploratory approach might manifest in a desire for less commitment and more independence, which could lead to misaligned expectations if not addressed openly."
        ]
    },
    "bonding-connecting": {
        "insights": [
            "You're prioritizing bonding with a partner. You're ready to put forth the time and effort to build a partnership that works. Nurturing the bond with your partner to keep it strong is your priority. You realize that while falling in love is easy, staying in love requires dedication and intention, and you think it's more than worth it.",
            "[User Name] is at a [Number] on the readiness scale, indicating a deep commitment to bonding and forming a lasting relationship. In contrast, [Compatibility Name] is at a [Number], showing a readiness to connect and deepen the relationship, but perhaps not yet at the stage of full commitment. This difference suggests that while you are both interested in a meaningful relationship, [Compatibility Name] may still be exploring the depths of the connection.",
            "In a friendship context, this means you are looking for a friend who is willing to invest in a close and enduring relationship, while [Compatibility Name] might be seeking to strengthen the bond but may not yet be ready for the level of commitment you desire. It's important to communicate openly about expectations and ensure that both parties are comfortable with the pace of the relationship's development.",
            "For a romantic partnership, your readiness for bonding signifies a desire for a committed and long-term relationship, where both partners are fully invested in each other's well-being and in building a future together. [Compatibility Name]'s connecting readiness indicates a willingness to deepen the emotional connection, but there may still be a need for further exploration before reaching the same level of commitment. Balancing these different stages of readiness is crucial for the relationship's success."
        ]
    },
    "bonding-bonding": {
        "insights": [
            "You're prioritizing bonding with a partner. You're ready to put forth the time and effort to build a partnership that works. Nurturing the bond with your partner to keep it strong is your priority. You realize that while falling in love is easy, staying in love requires dedication and intention, and you think it's more than worth it.",
            "[User Name] and [Compatibility Name] are both at a [Number] on the readiness scale, indicating a shared commitment to bonding and building a lasting relationship. This mutual dedication suggests that both of you are on the same page when it comes to investing in the relationship and working towards a future together.",
            "In terms of friendship, this shared readiness level means that both of you are seeking a deep and enduring connection. You value loyalty, trust, and mutual support, and are both willing to put in the effort to maintain a strong and meaningful friendship that stands the test of time.",
            "For a romantic partnership, this alignment in bonding readiness signifies a strong foundation for a committed and long-term relationship. Both of you are focused on nurturing the bond, facing challenges together, and creating a shared life based on mutual respect, love, and shared goals. This shared commitment is key to a fulfilling and lasting partnership."
        ]
    }
}